data_dir = "/var/lib/vector"

[api]
enabled = false

[sources.kafka_read_raw_data]
type = "kafka"
bootstrap_servers = "kafka:9092"
group_id = "consumer-group-name"
key_field = "message_key"
topics = [ "^(topic)-.+" ]

[sinks.kinesis_stream]
type = "aws_kinesis_streams"
inputs = [ "kafka_read_raw_data" ]
partition_key_field = "message_key"
compression = "none"
endpoint = "http://kinesis:4568"
stream_name = "stream1"

  [sinks.kinesis_stream.encoding]
  codec = "json"